services:
  mysql:
    image: mysql:8.4
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Klizos@123
      MYSQL_DATABASE: user_info
      MYSQL_USER: emp_1
      MYSQL_PASSWORD: qwerty
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_app_net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s




  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - ./env/backend/.env
    networks:
      - my_app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:

networks:
  my_app_net:
    driver: bridge
