services:
  mysql:
    image: mysql:latest
    container_name: db
    ports:
      - "0.0.0.0:3306:3306"
    env_file:
      - ./env/db/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/db/schema:/docker-entrypoint-initdb.d
    networks:
      - my_app_net
    restart: unless-stopped
  
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - my_app_net
    env_file:
      - ./env/backend/.env
      
volumes:
  mysql_data:

networks:
  my_app_net:
    driver: bridge