services:
  mysql:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - ./env/db/.env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
  
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - ./env/backend/.env
      
volumes:
  mysql_data: