name: Setup Environment Files
description: Create backend and DB .env files

inputs:
  backend_env:
    required: true
    description: Backend environment variables
  mysql_env:
    required: true
    description: MySQL DB environment variables
  test_env:
    required: true
    description: Test environment variables

runs:
  using: "composite"
  steps:
    - name: ðŸ“ Create .env Files
      run: |
        set -e

        mkdir -p env/backend env/db

        echo "ðŸ” Writing backend .env"
        printf "%s\n" "${{ inputs.backend_env }}" > env/backend/.env

        echo "ðŸ—„ï¸ Writing MySQL DB .env"
        printf "%s\n" "${{ inputs.mysql_env }}" > env/db/.env

        echo "ðŸ§ª Writing test .env"
        printf "%s\n" "${{ inputs.test_env }}" > .env.test

        echo "âœ… Environment files created successfully."
      shell: bash
