name: Run Pytest Tests
description: Run Python unit tests with environment variables

inputs:
  secret_key:
    description: Application secret key
    required: false
    default: ${{ secrets.TEST_SECRET_KEY }}
  mysql_host:
    required: false
    default: ${{ secrets.TEST_MYSQL_HOST }}
  mysql_port:
    required: false
    default: ${{ secrets.TEST_MYSQL_PORT }}
  mysql_database:
    required: false
    default: ${{ secrets.TEST_MYSQL_DATABASE }}
  mysql_user:
    required: false
    default: ${{ secrets.TEST_MYSQL_USER }}
  mysql_password:
    required: false
    default: ${{ secrets.TEST_MYSQL_PASSWORD }}

runs:
  using: "composite"
  steps:
    - run: pytest
      shell: bash
      env:
        PYTHONPATH: backend
        ENV: local
        SECRET_KEY: ${{ inputs.secret_key }}
        MYSQL_HOST: ${{ inputs.mysql_host }}
        MYSQL_PORT: ${{ inputs.mysql_port }}
        MYSQL_DATABASE: ${{ inputs.mysql_database }}
        MYSQL_USER: ${{ inputs.mysql_user }}
        MYSQL_PASSWORD: ${{ inputs.mysql_password }}
