name: Run Pytest Tests
description: Run Python unit tests with environment variables

inputs:
  secret_key:
    description: Application secret key
    required: false
    default: testsecretkey
  mysql_host:
    default: localhost
    required: false
  mysql_port:
    default: "3306"
    required: false
  mysql_database:
    default: user_info
    required: false
  mysql_user:
    default: emp_1
    required: false
  mysql_password:
    default: qwerty
    required: false
  test_path:
    description: Path to test files
    required: false
    default: backend/tests

runs:
  using: "composite"
  steps:
    - run: |
        echo "🔍 Running tests in: ${{ inputs.test_path }}"
        pytest ${{ inputs.test_path }} --maxfail=3 --disable-warnings --tb=short
      shell: bash
      env:
        ENV: local
        PYTHONPATH: backend
        SECRET_KEY: ${{ inputs.secret_key }}
        MYSQL_HOST: ${{ inputs.mysql_host }}
        MYSQL_PORT: ${{ inputs.mysql_port }}
        MYSQL_DATABASE: ${{ inputs.mysql_database }}
        MYSQL_USER: ${{ inputs.mysql_user }}
        MYSQL_PASSWORD: ${{ inputs.mysql_password }}
