name: Setup Python & Install Dependencies
description: Setup Python 3.12 and install pip packages
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
      shell: bash
