name: Reusable Docker CI

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.12'
        
      branch:
        required: false
        type: string
        default: 'padma'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies via Poetry
        run: |
          poetry install

      - name: Run tests
        run: |
          poetry run pytest

      - name: Build Docker image (only if tests pass)
        if: ${{ success() }}
        run: |
          make down && make build
