name: Call Reusable CI Workflow

on:
  push:
    branches: ["padma"]
  pull_request:
    branches: ["padma"]

jobs:
  use-reusable:
    uses: ./.github/workflows/ci-template.yml@padma
    with:
      python-version: '3.12'
